version: '3.8'

services:
  postgres:
    image: postgres:latest 
    container_name: patient_service_db
    restart: always
    env_file: 
      - ./.env
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  patient-service:
    build:
      context: .
      dockerfile: ./patient_service/Dockerfile 
    container_name: patient_service
    restart: always
    depends_on:
      - postgres  
      - kafka
    env_file:
      - ./.env
    ports:
      - "4000:4000" 

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    env_file:
      - ./.env
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"

volumes:
  postgres_data:
