version: "3.8"

services:
  # ================== INFRA ==================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # ================== BACKEND SERVICES ==================
  auth-service:
    image: arkad23/auth_service:latest
    container_name: auth-service
    ports:
      - "8086:8086"
      - "9086:9086"
    depends_on:
      - user-service

  user-service:
    image: arkad23/user_service:latest
    container_name: user-service
    ports:
      - "8085:8085"
      - "9085:9085"

  chat-service:
    image: arkad23/chat_service:latest
    container_name: chat-service
    ports:
      - "8087:8087"
      - "9087:9087"

  appointment-service:
    image: arkad23/appointment_service:latest
    container_name: appointment-service
    ports:
      - "8088:8088"
      - "9088:9088"
    depends_on:
      - user-service
      - kafka

  notification_service:
    image: arkad23/notification_service:latest
    container_name: notification_service
    ports:
      - "8089:8089"
    environment:
      - SPRING_MAIL_USERNAME=${GMAIL_USER}
      - SPRING_MAIL_PASSWORD=${GMAIL_PASS}
    depends_on:
      - kafka

  gateway:
    image: arkad23/gateway:latest
    container_name: gateway
    ports:
      - "8090:8090"
    depends_on:
      - auth-service
      - user-service
      - chat-service
      - appointment-service
      - notification_service

  # ================== FRONTEND ==================
  medibridge-client:
    image: arkad23/medibridge-client:latest
    container_name: medibridge-client
    ports:
      - "3000:3000"
    depends_on:
      - gateway

networks:
  default:
    name: medibridge-net
