apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: patient-app
spec:
  replicas: 1
  selector:
    matchLabels: { app: auth-service }
  template:
    metadata:
      labels: { app: auth-service }
    spec:
      containers:
        - name: auth
          image: auth-service:latest
          ports:
            - containerPort: 9091
            - containerPort: 8081
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8081 }
            initialDelaySeconds: 10
            periodSeconds: 10
