apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: patient-app
spec:
  selector:
    app: auth-service
  ports:
    - name: grpc
      port: 9091
      targetPort: 9091
    - name: http
      port: 8081
      targetPort: 8081
