grpc:
  client:
    userService:
      address: "static://localhost:9090"
      negotiationType: plaintext
    authService:
      address: "static://localhost:9091"
      negotiationType: plaintext
    appointmentService:
      address: "static://localhost:9094"
      negotiationType: plaintext
    chatService:
      address: "static://localhost:9095"
      negotiationType: plaintext
  server:
    port: -1