grpc:
  client:
    userService:
      address: "static://user-service:9085"
      negotiationType: plaintext
    authService:
      address: "static://auth-service:9086"
      negotiationType: plaintext
    appointmentService:
      address: "static://appointment-service:9088"
      negotiationType: plaintext
    chatService:
      address: "static://chat-service:9087"
      negotiationType: plaintext
  server:
    port: -1