user:
  service:
    url: https://user-service-kbh0.onrender.com/api/users

auth:
  service:
    url: https://auth-service-y5m5.onrender.com/api/auth

chat:
  service:
    url: https://chat-service-qtsr.onrender.com/api/chat

appointment:
  service:
    url: https://appointment-service-l1wg.onrender.com/api/appointments
