apiVersion: v1
kind: Namespace
metadata:
  name: medibridge
---
# ================== AUTH SERVICE ==================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: medibridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: arkad23/auth_service:latest
          ports:
            - containerPort: 8086
            - containerPort: 9086
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: medibridge
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 8086
      targetPort: 8086
    - name: grpc
      protocol: TCP
      port: 9086
      targetPort: 9086
  type: ClusterIP
---
# ================== USER SERVICE ==================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: medibridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: arkad23/user_service:latest
          ports:
            - containerPort: 8085
            - containerPort: 9085
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: medibridge
spec:
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085
    - name: grpc
      protocol: TCP
      port: 9085
      targetPort: 9085
  type: ClusterIP
---
# ================== CHAT SERVICE ==================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: medibridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: arkad23/chat_service:latest
          ports:
            - containerPort: 8087
            - containerPort: 9087
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: medibridge
spec:
  selector:
    app: chat-service
  ports:
    - name: http
      protocol: TCP
      port: 8087
      targetPort: 8087
    - name: grpc
      protocol: TCP
      port: 9087
      targetPort: 9087
  type: ClusterIP
---
# ================== APPOINTMENT SERVICE ==================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: medibridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: arkad23/appointment_service:latest
          ports:
            - containerPort: 8088
            - containerPort: 9088
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: medibridge
spec:
  selector:
    app: appointment-service
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: grpc
      protocol: TCP
      port: 9088
      targetPort: 9088
  type: ClusterIP
---

# ================== GATEWAY ==================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: medibridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: arkad23/gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: medibridge
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30080
  type: NodePort
---

